# Generated by Django 5.2.3 on 2025-06-25 04:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_message", models.TextField(verbose_name="Birinchi xabar")),
                (
                    "last_month_message",
                    models.TextField(verbose_name="Oxirgi oy xabari"),
                ),
                ("last_message", models.TextField(verbose_name="Oxirgi xabar")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.0,
                        help_text="Foiz (%) ko'rinishida",
                        max_digits=5,
                        verbose_name="Soliq foizi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin sozlamalari",
                "verbose_name_plural": "Admin sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="ExpensesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Izoh")),
            ],
            options={
                "verbose_name": "Xarajat kategoriyasi",
                "verbose_name_plural": "Xarajat kategoriyalari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Familiya"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqam formati: +998901234567",
                                regex="^\\+?998[0-9]{9}$",
                            )
                        ],
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Ishga olingan sana")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Lavozim"
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Maosh",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Xodim",
                "verbose_name_plural": "Xodimlar",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "stir",
                    models.CharField(
                        help_text="STIR raqami (9 raqam)", max_length=9, unique=True
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="To'liq nomi",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqam formati: +998901234567",
                                regex="^\\+?998[0-9]{9}$",
                            )
                        ],
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Izoh"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_companies",
                        to="main.employees",
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_companies",
                        to="main.employees",
                        verbose_name="Yangilagan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kompaniya",
                "verbose_name_plural": "Kompaniyalar",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "tender_status",
                    models.CharField(
                        choices=[
                            ("won", "Yutgan"),
                            ("lost", "Yutqazgan"),
                            ("canceled", "Bekor qilingan"),
                            ("not_participating", "Qatnashmagan"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Tender holati",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("contract", "Shartnoma"),
                            ("xt_xarid", "XT-xarid"),
                            ("xarid_uzex", "xarid.uzex"),
                        ],
                        max_length=50,
                        verbose_name="Turi",
                    ),
                ),
                ("started_date", models.DateField(verbose_name="Boshlangan sana")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                (
                    "contract_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Shartnoma summasi",
                    ),
                ),
                (
                    "contract",
                    models.FileField(
                        blank=True,
                        help_text="Shartnoma fayli",
                        null=True,
                        upload_to="contracts/%Y/%m/",
                        verbose_name="Shartnoma fayli",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Izoh"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "first_sms",
                    models.BooleanField(default=True, verbose_name="Birinchi SMS"),
                ),
                (
                    "last_month_sms",
                    models.BooleanField(default=True, verbose_name="Oxirgi oy SMS"),
                ),
                (
                    "last_sms",
                    models.BooleanField(default=True, verbose_name="Oxirgi SMS"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="main.company",
                        verbose_name="Kompaniya",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_services",
                        to="main.employees",
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_services",
                        to="main.employees",
                        verbose_name="Yangilagan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Xabar")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("first", "Birinchi xabar"),
                            ("last_month", "Oxirgi oy xabari"),
                            ("last", "Songi xabar"),
                        ],
                        default="first",
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Sana")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Yuborildi"),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yuborilgan sana"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="main.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirishnoma",
                "verbose_name_plural": "Bildirishnomalar",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Miqdor"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Qabul qilingan"),
                            ("pending", "Kutilmoqda"),
                            ("cancelled", "Bekor qilingan"),
                            ("unpaid", "To'lanmagan"),
                            ("partial", "Qisman to'langan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta"),
                            ("transfer", "O'tkazma"),
                        ],
                        max_length=20,
                        verbose_name="To'lov usuli",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="To'lov sanasi")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Soliq"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to="main.company",
                        verbose_name="Kompaniya",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_incomes",
                        to="main.employees",
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_incomes",
                        to="main.employees",
                        verbose_name="Yangilagan",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to="main.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daromad",
                "verbose_name_plural": "Daromadlar",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Miqdor"
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta"),
                            ("transfer", "O'tkazma"),
                            ("check", "Chek"),
                        ],
                        max_length=20,
                        verbose_name="To'lov usuli",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to="main.employees",
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="main.employees",
                        verbose_name="Xodim",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="main.expensescategory",
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Loyiha/Xizmat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="main.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xarajat",
                "verbose_name_plural": "Xarajatlar",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_status",
                    models.CharField(
                        choices=[
                            ("expected", "Kutilmoqda"),
                            ("preparing", "Tayorlanmoqda"),
                            ("delivering", "Yetkazilmoqda"),
                            ("submitted", "Topshirilgan"),
                        ],
                        default="expected",
                        max_length=20,
                        verbose_name="Xizmat holati",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Sana")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Izoh")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="main.service",
                        verbose_name="Xizmat",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.employees",
                        verbose_name="Yangilagan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat holati",
                "verbose_name_plural": "Xizmat holatlari",
                "ordering": ["-date"],
            },
        ),
    ]
