# Generated by Django 5.2.3 on 2025-06-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="position",
            field=models.CharField(
                choices=[
                    ("admin", "Rahbar"),
                    ("employee", "Xodim"),
                    ("accounted", "Bugalter"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
