# Generated by Django 5.2.3 on 2025-06-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_employees_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="password",
            field=models.CharField(
                default=1,
                help_text="Xodim login uchun paroli",
                max_length=128,
                verbose_name="Parol",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employees",
            name="position",
            field=models.CharField(
                choices=[
                    ("admin", "Rahbar"),
                    ("employee", "Xodim"),
                    ("accounted", "Bugalter"),
                ],
                max_length=50,
                verbose_name="Lavozim",
            ),
        ),
    ]
