# Generated by Django 5.2.3 on 2025-06-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_employees_password_alter_employees_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contract",
            field=models.FileField(blank=True, null=True, upload_to="contract/"),
        ),
        migrations.AlterField(
            model_name="company",
            name="full_name",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Xodiminin ism familyasi",
            ),
        ),
    ]
