# Generated by Django 5.2.3 on 2025-06-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_company_contract_alter_company_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="contract",
        ),
    ]
