# Generated by Django 5.1.1 on 2025-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_company_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="started_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Boshlangan sana"
            ),
        ),
    ]
