# Generated by Django 5.1.1 on 2025-06-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_service_started_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Qabul qilingan"),
                    ("pending", "Kutilmoqda"),
                    ("unpaid", "To'lanmagan"),
                    ("partial", "Qisman to'langan"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Holat",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="taxes",
            field=models.DecimalField(
                decimal_places=2, default=12, max_digits=10, verbose_name="Soliq"
            ),
        ),
    ]
