# Generated by Django 5.1.1 on 2025-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_income_status_alter_income_taxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Qabul qilingan"),
                    ("pending", "Kutilmoqda"),
                    ("partial", "Qisman to'langan"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Holat",
            ),
        ),
    ]
