# Generated by Django 5.1.1 on 2025-06-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_income_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="main.employees",
                verbose_name="Xodim",
            ),
        ),
    ]
