# Generated by Django 5.1.1 on 2025-06-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_expenses_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensescategory",
            name="tex",
            field=models.IntegerField(default=0),
        ),
    ]
