# Generated by Django 5.1.1 on 2025-07-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_rename_tex_expensescategory_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Soliq miqdori"
            ),
        ),
        migrations.AddField(
            model_name="expenses",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Soliq foizi"
            ),
        ),
        migrations.AddField(
            model_name="expenses",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=12, verbose_name="Jami miqdor"
            ),
            preserve_default=False,
        ),
    ]
