# Generated by Django 5.1.1 on 2025-07-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_expenses_tax_amount_remove_expenses_tax_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminsettings",
            name="tax_amount",
        ),
    ]
