# Generated by Django 4.2.7 on 2025-07-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_income_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='service',
            field=models.ForeignKey(help_text='Loyiha/Xizmat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.service', verbose_name='Xizmat'),
        ),
    ]
